---
title: CV
format:
  quarto-cv-pdf: default
author: Álvaro Canalejo-Molero
jobtitle: "Postdoctoral Researcher, Department of Political Science, University of Lucerne"
date: last-modified
address: "Frohburgstrasse, 3 · 6002 · Lucerne, Switzerland"
email: alvaro.canalejo@unilu.ch
# phone: "+41 078 267 5636"
orcid: 0000-0001-7980-0702 # orcid identifier
web: acanalejo.github.io
# github: ACanalejo
fontawesome: yes
nocite: '@*'
fontsize: 11pt
csl: apa-cv.csl
---

# Employment & Affiliations

*University of Lucerne*

&nbsp; Postdoctoral Researcher \hfill 2022 - current

&nbsp; External Lecturer \hfill 2022

*Autonomous University of Barcelona*

&nbsp; Visiting Fellow (hosted by *Enrique Hernández*) \hfill 2025

*London School of Economics & Political Science*

&nbsp; Visiting Fellow (hosted by *Chris J. Anderson*) \hfill 2021

# Education

PhD in Political and Social Sciences, *European University Institute* \hfill 2023

&nbsp;  Committee: Hanspeter Kriesi (supervisor), Elias Dinas, Chris J. Anderson, Ruth Dassonneville

MRes in Political and Social Sciences, *European University Institute* \hfill 2019

MSc in Social Sciences, *Carlos III-Juan March Institute, University Carlos III of Madrid* \hfill 2018

&nbsp; --- First Class

# Peer-Reviewed Publications

1. Moreno-Torres, J. P., Canalejo-Molero, Á., & López Ortega, A. (2025). When the party is over: Explaining the rise of the Spanish far-right SALF. *Research & Politics, 12*(3). [https://doi.org/10.1177/20531680251357602](https://doi.org/10.1177/20531680251357602)

# Working papers

Canalejo-Molero, Á., Cicchi, L., Ferreira da Silva, F., Garzia, D., Reiljan, A. & Trechsel A. H.  *Priming Common European and Democratic Values Does Not Reduce Affective Polarization* (Conditionally accepted, EPSR)

Ferreira da Silva, F., Canalejo-Molero, Á., Cicchi, L., Garzia, D., Reiljan, A. & Trechsel A. H. *Reducing Partisan Animosity with Voting Advice Applications (VAAs)* (Revise and resubmit, BJPols)

Padilla-Galviz, E. S. & Canalejo-Molero, Á. *Does Losing Affect Democratic Attitudes and Preferences among Rank-and-File Politicians? Theory and Evidence* [[Preprint](https://osf.io/preprints/osf/58csh_v1)] (Revise and resubmit, EJPR)

Canalejo-Molero, Á. & Le Corre Juratic, M. *Blinded by Out-group Hatred. Why does Radical Party Entry Reduce its Voters’ Satisfaction with Democracy?* [[Preprint](https://osf.io/7bfka)] (Revise and resubmit, EPSR)

&nbsp; --- Djøf Forlag prize for the best paper presented by a junior researcher at the 2023 Danish Political Science Association conference

&nbsp; --- Wilson award for the best paper on French politics presented at the 2022 APSA meeting

Canalejo-Molero, Á. & Le Corre Juratic, M. *When Losers Dissent: Affective Polarization and the Logic of Contestation* (Under review, BJPols)

Canalejo-Molero, Á., López Ortega, A. & Moreno-Torres, J. P. *A Theory of Relative State Devolution Preferences: Evidence and Implications* (Under review, CPS)

Canalejo-Molero, Á. *Boost or Backlash? The Heterogeneous Effects of Parliamentary Representation on Satisfaction with Democracy* [[Preprint](https://osf.io/ekymh)]

Canalejo-Molero, Á., Bürgisser, R., van Ditmars, M. M. & Trechsel, A. H. *The Political Conflict Potential of Digitalization* (Working paper available upon request)

Canalejo-Molero, Á. *Disruptive Elections and their Implications for Satisfaction with Democracy* (Working paper available upon request)

Canalejo-Molero, Á. *Does New Party Entry Increase Electoral Turnout? Quasi-Experimental Evidence from the 2015 Spanish Local Elections* (Working paper available upon request)

# Work in Progress

The Politicization of Digitalization (with Flechtner, M. & Trechsel, A. H.)

Early political socialization and school-based interventions (with Trechsel, A. H.)

Internal Migration and Regional Devolution Preferences (López Ortega, A. & Moreno-Torres, J. P)

The Political Consequences of Caregiving Policies (with Caihuelas Navajas, B. & Martín Cadenas, P.)

# Other Publications

Cicchi, L., Reiljan, A., Canalejo-Molero, Á., Ferreira da Silva, F., Garzia, D., Trechsel, A. H., & Fiselier, T. A. G. (2026). [*EU&I 2024 party and user dataset*](https://hdl.handle.net/1814/95154). EUI, RSC, Research Data.

Canalejo-Molero, Á. (2023). [*New party entry and political engagement: electoral turnout and satisfaction with democracy*](https://hdl.handle.net/1814/75692). Florence: European University Institute, EUI, SPS, PhD Thesis.

# Research Grants (as PI or Co-PI)

UniLu FoKo Preparatory Funding *(22,330 CHF ≈ 24,153€)*, with Trechsel, A. H. \hfill 2026

UniLu FaFoFö Funding *(2,000 CHF ≈ 2,142€)* \hfill 2025

Small Grant Aarhus University *(35,000 DKK ≈ 4,686€)*, with Le Corre Juratic, M. \hfill 2024

UniLu FoKo Project Funding *(12,231 CHF ≈ 13,101€)*, with López Ortega, A. & Padilla Moreno-Torres, J. \hfill 2023

EUI Mission Funding for Research Activities *(2,547€)*, with Le Corre Juratic, M. \hfill 2022

# Additional Experience in Research Projects

[DIGIPOL](https://www.unilu.ch/en/faculties/faculty-of-humanities-and-social-sciences/institutes-departements-and-research-centres/department-of-political-science/research/digitalization-and-political-conflict-parties-voters-and-electoral-alignment-digipol/) (Scientific Coordinator), [EU&I 2024](https://euandi.eu/en/about/overview.html) (Scientific Committee), [SOLID](https://solid-erc.eu/), [POLCON](https://www.eui.eu/projects/polcon), [EUANDI2019](https://euandi2019.eu/survey/default/EN), [¿Por qué odiamos la politica?](https://www.iesa.csic.es/proyectos/por-que-odiamos-la-politica/), [Parlamentarios y Sociedad](https://www.upo.es/investiga/ptyp/es/project/parlamentarios-y-sociedad/), [ICOSOP](https://www.upo.es/investiga/ptyp/wp-content/uploads/2018/04/ICOSOP_Informe_seguimiento_3.pdf)

# Invited Talks and Workshops (selected)

ECPR Joint Sessions \hfill 2025

UAB DEC Seminar \hfill 2025

UB Workshop on The Political Economy of AI \hfill 2024

UZH-DSI Digital Democracy Workshop \hfill 2024, 2025

IPP-CSIC Research Seminar \hfill 2024

EUI Towards Affective Depolarization Workshop \hfill 2024

Luiss Guido Carli Cluster of Excelence on Elections (CISE) Seminar \hfill 2024

EU Comission - Joint Research Centre (JRC) DIGCLASS Workshop \hfill 2023

CERIUM-FMSH New Challenges to Democracy Workshop \hfill 2022

# Conference Presentations (selected)

American Political Science Association (APSA) \hfill 2024, 2023\*, 2022

European Political Science Association (EPSA) \hfill 2025, 2024\*, 2023\*, 2022, 2021

European Political Science Society \hfill 2026\*

European Consortium of Political Research (ECPR) \hfill 2026\*, 2025\*, 2024\*, 2023\*

Council of European Studies (CES) \hfill 2023

Midwest Political Science Association (MPSA) \hfill 2025\*, 2023

International Political Science Association (IPSA) \hfill 2025

Computational Text Analysis Conference (COMPTEXT) \hfill 2023

Swiss Political Science Association (SPSA) \hfill 2026, 2025\*, 2024

Spanish Political Science Association (AECPA) \hfill 2026\*, 2024

```{=latex}
\vspace{0.2em}
{\scriptsize  \hfill *Accepted but not attended, or not yet attended.}
```

# Teaching

Graduate level

&nbsp; [Research Design and Methods in Quantitative Research](https://github.com/ACanalejo/rdmqr_unilu2025), *University of Lucerne*  \hfill 2024, 2025

Undergraduate level

&nbsp; [The Politics of Democratic Backsliding](https://github.com/ACanalejo/dem_backsliding_unilu2026),  *University of Lucerne*  \hfill 2026

&nbsp; [Culture and Politics](https://github.com/ACanalejo/politicalculture_unilu2025),  *University of Lucerne*  \hfill 2024, 2025

&nbsp; [Electoral Behavior and Party Competition: Continuity and Change in WE](https://github.com/ACanalejo/ebpc_unilu2023), *University of Lucerne*  \hfill 2022, 2023

# Supervision

Ten MA theses (five as main supervisors) and nine BA theses (all as main supervisors), including *expected*.

# Public Outreach

[Cadena Ser](https://cadenaser.com/nacional/2025/08/26/un-ano-de-alvise-como-eurodiputado-promesas-incumplidas-conflictos-y-una-caida-en-picado-en-las-encuestas-cadena-ser/), [El Periódico](https://www.elperiodico.com/es/politica/20240608/test-orientar-voto-elecciones-europeas-9j-dv-103484468), [Onda Cero](https://www.ondacero.es/elecciones/europeas/quien-votar-elecciones-europeas-test-saber-partido-que-identificas_202406076662b9798fd52100010aeba8.html), [VoxEurop](https://voxeurop.eu/en/who-vote-european-elections-app-help/), [Times of Malta](https://timesofmalta.com/article/unsure-vote-european-elections-this-online-tool-help.1092745), [The Irish Times](https://www.irishtimes.com/politics/2024/05/20/which-political-parties-match-your-views-new-online-tool-lets-voters-check-the-parties-they-are-aligned-with/), [Fondation Maison des sciences de l'homme](https://www.fmsh.fr/en/publications/why-arent-radical-voters-more-satisfied-democracy-when-entering-political-system-role), ElPaís ([1](https://elpais.com/politica/2016/07/05/actualidad/1467717044_250844.html), [2](https://elpais.com/politica/2015/12/26/actualidad/1451146607_312379.html))

# Scholarships & Awards (selected)

Erasmus+ Scholarship for Visiting PhDs, *European Comission* \hfill 2021

Salvador de Madariaga doctoral Scholarship, *Spanish Ministry of Education & European Comission* \hfill 2018 - 2023

UC3M Scholarship of Excellence for Graduate Studies, *University Carlos III of Madrid* \hfill 2017 - 2018

Best GPA of the Promotion Award, *University Pablo de Olavide* \hfill 2016

# Professional Service

Convenor of the *PolSem* Brown Bag Seminar, *University of Lucerne* \hfill 2023 - current

Co-organiser of the [Political Behaviour Colloquium](https://sites.google.com/site/euipolbehaviour/), *European University Institute* \hfill 2020 - 2021

# Journal Reviews

Invited reviewer for *American Journal of Political Science*, *Journal of Politics*, *European Journal of Political Research*, *Public Opinion Quarterly*, *Government & Opposition*, *Research and Politics*, *Politics & Governance*, *Acta Politica*, *Swiss Political Science Review* and *German Politics*

# Professional Associations Membership

[APSA](https://apsanet.org/), [EPSS](https://epssnet.org/), [EPSA](https://epsanet.org/), [ECPR](https://ecpr.eu/), [IPSA](https://www.ipsa.org/), [DSI](https://www.dsi.uzh.ch/en.html), [AECPA](https://www.aecpa.es/)

# Additional Training

Oxford Spring School in Advanced Research Methods, *Oxford University* \hfill 2023

EUI Introduction to Teaching in Higher Education, *European University Institute* \hfill 2020

6th Leuven-Montréal Winter School on Elections, *University of Montréal* \hfill 2020

RECSM-UPF Summer School in Survey Methodology, *Pompeu-Fabra University* \hfill 2019

# Skills

\noindent
\begin{minipage}[t]{0.48\textwidth}
Programming: \emph{R (advanced), Python (beginner)}\\[0.5em]
Statistical Software: \emph{RStudio, Stata, SPSS, Excel}\\[0.5em]
Surveys: \emph{Qualtrics}\\[0.5em]
Version Control System: \emph{GitHub}
\end{minipage}
\hfill
\begin{minipage}[t]{0.48\textwidth}
Text Processor: \emph{Quarto, Overleaf}, \LaTeX, \emph{Office} \\[0.5em]
Reference Management: \emph{Zotero}\\[0.5em]
Languages: \emph{English (proficient), Spanish (native), Italian (advanced), French (beginner), German (beginner)}
\end{minipage}

# Referees

\noindent
\begin{minipage}[t]{0.48\textwidth}
\raggedright
\textbf{Prof. Hanspeter Kriesi} \\
PhD Supervisor \\
SPS Part-Time Professor \\
European University Institute \\
\href{mailto:hanspeter.kriesi@alumniprofs.eui.eu}{hanspeter.kriesi@alumniprofs.eui.eu}
\end{minipage}
\hfill
\begin{minipage}[t]{0.48\textwidth}
\raggedright
\textbf{Prof. Alexander H. Trechsel} \\
Postdoc Supervisor \\
Chair of Political Behaviour \& Communication \\
University of Lucerne \\
\href{mailto:alexander.trechsel@unilu.ch}{alexander.trechsel@unilu.ch}
\end{minipage}
