---
output: 
  pdf_document:
    template: ../templates/svm-latex-cv_mod.tex
geometry: margin=1in
linestretch: 0.5

title: "long_cv"
author: Álvaro Canalejo-Molero

jobtitle: "Postdoctoral Researcher, Department of Political Science, University of Lucerne"
address: "Frohburgstrasse, 3 · 6002 · Luzern, Switzerland"
fontawesome: yes
email: alvaro.canalejo@unilu.ch
# phone: "+41 078 267 5636"
github: ACanalejo
twitter: CanalejoAlvaro
# osf: "Enter 5 digit osf string here"
web: acanalejo.github.io
updated: yes

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue

---

\vspace{1 mm}
# Research Interests
\vspace{1 mm}

> Comparative politics, political behavior, political sociology, quantitative methodology

\vspace{1 mm}
# Academic Positions
\vspace{1 mm}

> **Postdoctoral Researcher** \hfill 2022 - current \vspace{0.1 mm}

> University of Lucerne \vspace{2 mm}

> **PhD Researcher** \hfill 2018 - current \vspace{0.1 mm}

> European University Institute \vspace{2 mm}

> **External Lecturer** \hfill 2022 \vspace{0.1 mm}

> University of Lucerne \vspace{2 mm}

> **Visiting PhD Researcher** \hfill 2021 \vspace{0.1 mm}

> London School of Economics & Political Science \vspace{0.1 mm}

> Host: Dr. Chris Anderson \vspace{2 mm}

\vspace{1 mm}
# Education
\vspace{1 mm}

> **Ph.D. in Political and Social Sciences** \hfill (expected) 2023 \vspace{0.1 mm}

> European University Institute \vspace{0.1 mm}
   
> Supervisor: Dr. Hanspeter Kriesi \vspace{2 mm}
   
> **M.Res. in Political and Social Sciences** \hfill 2019 \vspace{0.1 mm}
   
> European University Institute \vspace{2 mm}
   
> **M.A. in Social Sciences** \hfill 2018 \vspace{0.1 mm}
   
> Carlos III-Juan March Institute, University Carlos III of Madrid \vspace{0.1 mm}
   
> First Class \vspace{2 mm}
   
> **B.A. in Political Science and Public Management** \hfill 2016 \vspace{0.1 mm}
   
> Pablo de Olavide University (Seville, Spain) \vspace{0.1 mm}
   
> Suma Cum Laude \vspace{2 mm}
   
> **B.A. in Law** \hfill 2015 \vspace{0.1 mm}
   
> Pablo de Olavide University (Seville, Spain) \vspace{0.1 mm}
   
> Suma Cum Laude \vspace{0.1 mm}
   
\vspace{1 mm}
# Work-in-progress
\vspace{1 mm}

> Boost or Backlash? The Heterogeneous Effects of Parliamentary Representation on Satisfaction with Democracy (*working paper*) \vspace{2 mm}

> Why does Radical Party Entry Reduce Satisfaction with Democracy? The Role of Affective Polarization (*working paper*) *with Morgan Le Corre Juratic* \vspace{2 mm}

> Disruptive Elections and their Implications for Satisfaction with Democracy (*working paper*) \vspace{2 mm}

> Does New Party Entry Increase Electoral Turnout? Quasi-Experimental Evidence from the 2015 Spanish Local Elections (*working paper*) \vspace{2 mm}

> The Politicization of Digitalization: How Political Parties Structure Nascent Conflicts over Digitalization Issues (*work in progress*) *with Mathilde M. van Ditmars & Alexander H. Trechsel* \vspace{2 mm}


\vspace{1 mm}
# Research Projects
\vspace{1 mm}

*As Principal Investigator*\vspace{1 mm}

> [NewRadRight](https://acanalejo.github.io/research/#research-projects) -- see [Pre-Analysis Plan](https://github.com/ACanalejo/ACanalejo.github.io/raw/master/_drafts/french_survey_2022_pap.pdf) \hfill 2022 \vspace{0.1 mm}
   
> EUI Mission Funding for Research Activities. PIs: Álvaro Canalejo-Molero (EUI) and Morgan Le Corre Juratic (EUI). \vspace{2 mm}

*As Member of the Research Team*\vspace{1 mm}

> Postdoctoral Researcher · [DIGIPOL](https://www.unilu.ch/en/faculties/faculty-of-humanities-and-social-sciences/institutes-departements-and-research-centres/department-of-political-science/research/digitalization-and-political-conflict-parties-voters-and-electoral-alignment-digipol/) \hfill 2022 - current \vspace{0.1 mm}

> Swiss National Science Foundation (SNSF). PI: Alexander Trechsel (UNILU). \vspace{2 mm}

> Research Assistant · [SOLID](https://solid-erc.eu/) \hfill 2020 - 2021 \vspace{0.1 mm}

> ERC Synergy Grant. PIs: Hanspeter Kriesi (EUI), WaltraudSchelkle (LSE), and Maurizio Ferrera (UniMi). \vspace{2 mm}

> Research Assistant · [POLCON](https://www.eui.eu/projects/polcon) \hfill 2019 - 2020 \vspace{0.1 mm}
   
> ERC Advanced Grant. PIs: Hanspeter Kriesi (EUI). \vspace{2 mm}
  
> Research Assistant · [EUANDI2019](https://euandi2019.eu/survey/default/EN) \hfill 2019 \vspace{0.1 mm}
   
> European Union’s Rights, Equality and Citizenship Programme 2014 - 2020. PIs: Lorenzo Cicchi (EUI), Diego Garzia (UNILU), Alexander H. Trechsel (UNILU) and Elie Michel (UNILU). \vspace{2 mm}
  
> Research Internship · [¿Por qué odiamos la politica?](https://www.iesa.csic.es/proyectos/por-que-odiamos-la-politica/) \hfill 2015 \vspace{0.1 mm}
  
> Center of Andalusian Studies (CEA). PIs: Ernesto Ganuza (IESA-CSIC) and Joan Font (IESA-CSIC). \vspace{2 mm}
   
> Research Collaborator · [Parlamentarios y Sociedad](https://www.upo.es/investiga/ptyp/es/project/parlamentarios-y-sociedad/) \hfill 2015 \vspace{0.1 mm}
  
> Spanish Ministry of Economy. PIs: Xavier Coller (UPO). \vspace{2 mm}
  
> Research Collaborator · [ICOSOP](https://www.upo.es/investiga/ptyp/wp-content/uploads/2018/04/ICOSOP_Informe_seguimiento_3.pdf) \hfill 2014 \vspace{0.1 mm}
  
> Andalusian Government. PIs: Xavier Coller (UPO) and Jean Baptiste Harguideguy (UPO).

\vspace{1 mm}
# Teaching
\vspace{1 mm}

> [Electoral Behavior and Party Competition: Continuity and Change in WE](https://github.com/ACanalejo/ebpc_unilu2023) \hfill 2023 \vspace{0.1 mm}

> University of Lucerne \vspace{0.1 mm}

> [Comparative Western European Party Systems: Continuity and Change](https://github.com/ACanalejo/cwps_continuity_and_change_unilu2022) \hfill 2022 \vspace{0.1 mm}

> University of Lucerne \vspace{0.1 mm}

\vspace{1 mm}
# Conference Presentations & Invited Talks
\vspace{1 mm}

> European Survey Research Association Conference (ESRA), *accepted* \hfill 2023 \vspace{0.1 mm}
   
> Milan, Italy \vspace{2 mm}

> 29th Conference of the Council for European Studies (CES), *accepted* \hfill 2023 \vspace{0.1 mm}
   
> Reykjavik, Iceland \vspace{2 mm}

> 80th Annual Midwest Political Science Association Conference (MPSA), *accepted* \hfill 2023 \vspace{0.1 mm}
   
> Chicago, US \vspace{2 mm}

> CERIUM-FMSH New Challenges to Democracy Workshop \hfill 2022 \vspace{0.1 mm}
   
> Montréal, Canada \vspace{2 mm}
  
> 118th Annual Meeting of the American Political Science Association (APSA) \hfill 2022 \vspace{0.1 mm}
  
> Montréal, Canada\vspace{2 mm}
  
> 12th Annual Conference of the European Political Science Association (EPSA) \hfill 2022 \vspace{0.1 mm}
  
> Prague, Czech republic \vspace{2 mm}
  
> Research Workshop in European Studies - LSE European Institute \hfill 2021 \vspace{0.1 mm}
  
> London, UK \vspace{2 mm}
  
> 11th Annual Conference of the European Political Science Association (EPSA) \hfill 2021 \vspace{0.1 mm}
   
> Online \vspace{2 mm}
  
> 12th European Graduate Network Conference\hfill 2021 \vspace{0.1 mm}
  
> Online \vspace{2 mm}
   
> The Transformation of European Politics Workshop - EUI \hfill 2020 \vspace{0.1 mm}
  
> Online \vspace{2 mm}
  
> 6th Leuven-Montréal Winter School on Elections \hfill 2020 \vspace{0.1 mm}
  
> Montréal, Canada\vspace{2 mm}
  
> EUI Political Behaviour Colloquium \hfill 2020 \vspace{0.1 mm}
  
> Florence, Italy\vspace{2 mm}

> 1st Spanish Congress of the European Social Survey \hfill 2018 \vspace{0.1 mm}
  
> Madrid, Spain \vspace{0.1 mm}
 
\vspace{1 mm}
# Complementary Academic Formation
\vspace{1 mm}

> Oxford Spring School in Advanced Research Methods \hfill 2023

>  Oxford University \vspace{2 mm}

> Introduction to Teaching in Higher Education \hfill 2020
   
>  European University Institute \vspace{2 mm}
   
> 6th Leuven-Montréal Winter School on Elections \hfill 2020
  
> University of Montréal (Canada) \vspace{2 mm}
  
> RECSM-UPF Summer School in Survey Methodology \hfill 2019
   
> Pompeu-Fabra University (Barcelona, Spain) \vspace{2 mm}

\vspace{1 mm}
# Research Grants
\vspace{1 mm}

> Mission Funding for Research Activities *(2,547€)*. *With Morgan Le Corre Juratic.* \hfill 2022 \vspace{0.1 mm}

> European University Institute \vspace{2 mm}

\vspace{1 mm}
# Scholarships & Awards
\vspace{1 mm}


> Erasmus+ Scholarship for Visiting PhDs \hfill 2021 \vspace{0.1 mm}
  
> European Comission \vspace{2 mm}
  
> `Salvador de Madariaga' predoctoral Scholarship \hfill 2018 - 2022 \vspace{0.1 mm}
  
> Spanish Ministry of Education and European Comission \vspace{2 mm}
  
> UC3M scholarship of excellence for graduate studies \hfill 2017 - 2018 \vspace{0.1 mm}
  
> University Carlos III of Madrid (Spain) \vspace{2 mm}
  
>  Best GPA of the Promotion Award \hfill 2016 \vspace{0.1 mm}
  
> University Pablo de Olavide (Spain) \vspace{2 mm}
  
> Grant for Beginner Researchers \hfill 2014 \vspace{0.1 mm}
  
> University Pablo de Olavide (Spain) \vspace{2 mm}
  
> Best GPA of the Promotion at the First Course Award \hfill 2011 \vspace{0.1 mm}
  
> University Pablo de Olavide (Spain) \vspace{0.1 mm}

\vspace{1 mm}
# Professional Service
\vspace{1 mm}

> Discussant of the panel *Democratic Expansion, Protests and Compulsory Voting* \hfill 2022 \vspace{0.1 mm}

> 118th APSA \vspace{2 mm}

> Chair of the panel *Electoral Rules and Voter Turnout* \hfill 2021 \vspace{0.1 mm}

> 11th EPSA \vspace{2 mm}

> Co-organiser of the [Political Behaviour Colloquium](https://sites.google.com/site/euipolbehaviour/) \hfill 2020 - 2021
   
> European University Institute


\vspace{1 mm}
# Technical Skills
\vspace{1 mm}

> **Programming Languages:** R (advanced), Python (beginer)  \vspace{1 mm}
  
> **Statistical Softwares:** RStudio, Stata, SPSS, Excel  \vspace{1 mm}

> **Surveys:** Qualtrics  \vspace{1 mm}
  
>  **Version Control System:** GitHub  \vspace{1 mm}
  
> **Text Processors:** RMarkdown, \LaTeX, Office  \vspace{1 mm}
  
> **Reference Management:** Zotero \vspace{1 mm}

\vspace{1 mm}
# Languages
\vspace{1 mm}

> English (proficient)  \vspace{1 mm}

> Spanish (native)  \vspace{1 mm}
 
> Italian (advanced)  \vspace{1 mm}
   
> French (beginner) \vspace{1 mm}



